// GENERATED by tools/fusion_ab/compare_stages.py --viz-data -- do not hand-edit.
// Re-run it after a new sweep to refresh visualizations/fusion_ab.html.
window.FUSION_AB = {
 "classes": 4,
 "seed": 0,
 "frames": 30,
 "machines": {
  "1": {
   "label": "1",
   "name": "MacBook (Apple M5)",
   "gpu": "Apple M5, 10-core GPU (Metal 4)",
   "cpu": "VirtualApple @ 2.50GHz x10",
   "platform": "Linux-6.12.76-linuxkit-x86_64-with-glibc2.39",
   "arch": "x86_64"
  },
  "2": {
   "label": "2",
   "name": "NVIDIA Thor 4",
   "gpu": "NVIDIA Thor ([N/A], driver 580.00)",
   "cpu": "aarch64 x14",
   "platform": "Linux-6.8.12-tegra-aarch64-with-glibc2.39",
   "arch": "aarch64"
  }
 },
 "stat_columns": [
  "mean",
  "p25",
  "median",
  "p75",
  "max"
 ],
 "stage_order": [
  "END-TO-END",
  "decode",
  "kinematic checks",
  "mspsf phase-1 fusion",
  "buckets+support",
  "attribute checks",
  "consistency+ledger",
  "reputation+gate",
  "db record+flush",
  "sort tracking"
 ],
 "concurrent_stages": [
  "sort tracking"
 ],
 "stage_labels": {
  "END-TO-END": "END-TO-END",
  "decode": "decode SDSM messages",
  "kinematic checks": "kinematic checks",
  "mspsf phase-1 fusion": "matching: MS-PSF phase-1 fusion",
  "buckets+support": "bucket derivation + support",
  "attribute checks": "attribute checks",
  "consistency+ledger": "consistency scoring + ledger",
  "reputation+gate": "reputation update + gate",
  "db record+flush": "DB record + flush",
  "sort tracking": "SORT tracking (concurrent)"
 },
 "axes": [
  {
   "axis": "agents",
   "x": [
    2,
    5,
    10
   ],
   "fixed_label": "256 objects",
   "panels": [
    {
     "key": "e2e",
     "title": "End-to-end (flush_frame)"
    },
    {
     "key": "fusion",
     "title": "Matching / fusion stage (MS-PSF phase-1)"
    }
   ],
   "machines": [
    "1",
    "2"
   ],
   "data": {
    "e2e": {
     "1": {
      "reference": {
       "median": [
        555.7306,
        2442.0797,
        9847.8548
       ],
       "p95": [
        565.1115,
        6615.301,
        49325.8023
       ]
      },
      "modified": {
       "median": [
        139.9614,
        326.9052,
        617.9608
       ],
       "p95": [
        390.989,
        914.4075,
        1007.6492
       ]
      }
     },
     "2": {
      "reference": {
       "median": [
        763.2142,
        2916.486,
        9628.2243
       ],
       "p95": [
        766.7503,
        2924.6187,
        9664.9113
       ]
      },
      "modified": {
       "median": [
        100.5778,
        230.8846,
        590.7701
       ],
       "p95": [
        105.0314,
        235.9736,
        623.6092
       ]
      }
     }
    },
    "fusion": {
     "1": {
      "reference": {
       "median": [
        550.7565,
        2427.7014,
        9774.104
       ],
       "p95": [
        559.8698,
        6579.0235,
        49084.2479
       ]
      },
      "modified": {
       "median": [
        131.5446,
        306.9554,
        579.6343
       ],
       "p95": [
        380.0967,
        878.9088,
        962.7603
       ]
      }
     },
     "2": {
      "reference": {
       "median": [
        760.0384,
        2908.664,
        9610.526
       ],
       "p95": [
        763.6924,
        2916.8143,
        9647.2517
       ]
      },
      "modified": {
       "median": [
        97.4674,
        223.3062,
        572.8271
       ],
       "p95": [
        101.5636,
        228.3628,
        604.9175
       ]
      }
     }
    }
   }
  },
  {
   "axis": "objects",
   "x": [
    16,
    32,
    64,
    128,
    256
   ],
   "fixed_label": "2 agents",
   "panels": [
    {
     "key": "e2e",
     "title": "End-to-end (flush_frame)"
    },
    {
     "key": "fusion",
     "title": "Matching / fusion stage (MS-PSF phase-1)"
    }
   ],
   "machines": [
    "1",
    "2"
   ],
   "data": {
    "e2e": {
     "1": {
      "reference": {
       "median": [
        9.4918,
        23.8637,
        75.8368,
        218.1381,
        679.8283
       ],
       "p95": [
        9.799,
        33.9109,
        129.1505,
        423.7108,
        929.355
       ]
      },
      "modified": {
       "median": [
        4.8632,
        9.353,
        19.2335,
        45.4045,
        100.3647
       ],
       "p95": [
        5.1369,
        9.562,
        22.8127,
        49.42,
        122.2149
       ]
      }
     },
     "2": {
      "reference": {
       "median": [
        10.0063,
        24.2656,
        67.9397,
        218.0504,
        768.9905
       ],
       "p95": [
        10.5314,
        24.7078,
        68.4467,
        219.1747,
        771.4533
       ]
      },
      "modified": {
       "median": [
        5.3114,
        10.2463,
        20.266,
        42.794,
        99.0223
       ],
       "p95": [
        5.5133,
        10.5119,
        20.7079,
        43.425,
        99.9279
       ]
      }
     }
    },
    "fusion": {
     "1": {
      "reference": {
       "median": [
        8.9882,
        22.9614,
        73.9258,
        214.688,
        673.6685
       ],
       "p95": [
        9.3388,
        32.7508,
        125.8517,
        418.3128,
        919.6696
       ]
      },
      "modified": {
       "median": [
        4.4425,
        8.5792,
        17.7475,
        42.2005,
        93.9424
       ],
       "p95": [
        4.7206,
        8.7888,
        21.1375,
        46.086,
        115.0941
       ]
      }
     },
     "2": {
      "reference": {
       "median": [
        9.5732,
        23.6596,
        66.9899,
        216.3599,
        765.8192
       ],
       "p95": [
        10.0379,
        24.0804,
        67.3534,
        217.355,
        768.2916
       ]
      },
      "modified": {
       "median": [
        4.9525,
        9.6636,
        19.2949,
        41.0663,
        95.876
       ],
       "p95": [
        5.1197,
        9.9,
        19.6908,
        41.7718,
        96.826
       ]
      }
     }
    }
   }
  }
 ],
 "tables": {
  "1": [
   {
    "axis": "agents",
    "x": 2,
    "title": "2 agents &times; 256 objects",
    "stages": {
     "modified": {
      "END-TO-END": {
       "mean": 165.5116,
       "p25": 114.8784,
       "median": 139.9614,
       "p75": 188.4423,
       "max": 403.6165
      },
      "decode": {
       "mean": 4.4467,
       "p25": 3.3135,
       "median": 3.7491,
       "p75": 5.3297,
       "max": 10.8622
      },
      "kinematic checks": {
       "mean": 1.9663,
       "p25": 1.5877,
       "median": 1.8881,
       "p75": 2.2781,
       "max": 2.8778
      },
      "mspsf phase-1 fusion": {
       "mean": 155.7939,
       "p25": 107.5422,
       "median": 131.5446,
       "p75": 170.4348,
       "max": 383.9783
      },
      "buckets+support": {
       "mean": 1.356,
       "p25": 0.6985,
       "median": 0.8333,
       "p75": 1.064,
       "max": 10.5075
      },
      "attribute checks": {
       "mean": 0.563,
       "p25": 0.4142,
       "median": 0.4764,
       "p75": 0.5982,
       "max": 1.5882
      },
      "consistency+ledger": {
       "mean": 1.1719,
       "p25": 0.7556,
       "median": 0.836,
       "p75": 1.097,
       "max": 6.6011
      },
      "reputation+gate": {
       "mean": 0.0294,
       "p25": 0.0172,
       "median": 0.0213,
       "p75": 0.0353,
       "max": 0.0998
      },
      "db record+flush": {
       "mean": 0.1844,
       "p25": 0.1078,
       "median": 0.14,
       "p75": 0.2205,
       "max": 0.4777
      },
      "sort tracking": {
       "mean": 34.8512,
       "p25": 24.7468,
       "median": 28.0419,
       "p75": 41.1096,
       "max": 88.8174
      }
     },
     "reference": {
      "END-TO-END": {
       "mean": 557.0004,
       "p25": 554.4052,
       "median": 555.7306,
       "p75": 558.8731,
       "max": 571.92
      },
      "decode": {
       "mean": 2.4021,
       "p25": 2.3844,
       "median": 2.4026,
       "p75": 2.417,
       "max": 2.4554
      },
      "kinematic checks": {
       "mean": 1.1485,
       "p25": 1.1254,
       "median": 1.1364,
       "p75": 1.1512,
       "max": 1.4047
      },
      "mspsf phase-1 fusion": {
       "mean": 552.0085,
       "p25": 549.4622,
       "median": 550.7565,
       "p75": 553.9068,
       "max": 566.9123
      },
      "buckets+support": {
       "mean": 0.5116,
       "p25": 0.5006,
       "median": 0.5043,
       "p75": 0.52,
       "max": 0.5505
      },
      "attribute checks": {
       "mean": 0.2999,
       "p25": 0.2935,
       "median": 0.2988,
       "p75": 0.3047,
       "max": 0.3389
      },
      "consistency+ledger": {
       "mean": 0.5376,
       "p25": 0.5295,
       "median": 0.5328,
       "p75": 0.5437,
       "max": 0.5754
      },
      "reputation+gate": {
       "mean": 0.0134,
       "p25": 0.0122,
       "median": 0.0132,
       "p75": 0.0139,
       "max": 0.0201
      },
      "db record+flush": {
       "mean": 0.0787,
       "p25": 0.0705,
       "median": 0.0765,
       "p75": 0.0823,
       "max": 0.1336
      },
      "sort tracking": {
       "mean": 17.4586,
       "p25": 17.1614,
       "median": 17.3026,
       "p75": 17.5345,
       "max": 20.146
      }
     }
    }
   },
   {
    "axis": "agents",
    "x": 10,
    "title": "10 agents &times; 256 objects",
    "stages": {
     "modified": {
      "END-TO-END": {
       "mean": 677.4294,
       "p25": 602.0806,
       "median": 617.9608,
       "p75": 699.6229,
       "max": 1026.192
      },
      "decode": {
       "mean": 19.0452,
       "p25": 15.7202,
       "median": 16.1256,
       "p75": 18.3071,
       "max": 54.1523
      },
      "kinematic checks": {
       "mean": 7.7792,
       "p25": 7.1533,
       "median": 7.4608,
       "p75": 8.0716,
       "max": 10.4343
      },
      "mspsf phase-1 fusion": {
       "mean": 637.9209,
       "p25": 567.0922,
       "median": 579.6343,
       "p75": 664.015,
       "max": 984.1103
      },
      "buckets+support": {
       "mean": 5.1809,
       "p25": 4.672,
       "median": 4.8916,
       "p75": 5.3075,
       "max": 7.186
      },
      "attribute checks": {
       "mean": 2.0217,
       "p25": 1.8824,
       "median": 1.9234,
       "p75": 2.0123,
       "max": 2.7127
      },
      "consistency+ledger": {
       "mean": 5.2825,
       "p25": 4.7902,
       "median": 5.0147,
       "p75": 5.3334,
       "max": 7.229
      },
      "reputation+gate": {
       "mean": 0.0386,
       "p25": 0.0296,
       "median": 0.0315,
       "p75": 0.0382,
       "max": 0.1127
      },
      "db record+flush": {
       "mean": 0.1605,
       "p25": 0.1087,
       "median": 0.1229,
       "p75": 0.1662,
       "max": 0.5404
      },
      "sort tracking": {
       "mean": 119.8757,
       "p25": 106.142,
       "median": 113.4295,
       "p75": 124.9659,
       "max": 176.093
      }
     },
     "reference": {
      "END-TO-END": {
       "mean": 17571.3293,
       "p25": 8775.855,
       "median": 9847.8548,
       "p75": 27308.5063,
       "max": 51451.9979
      },
      "decode": {
       "mean": 42.3364,
       "p25": 13.8743,
       "median": 15.7001,
       "p75": 37.8282,
       "max": 309.2553
      },
      "kinematic checks": {
       "mean": 14.8074,
       "p25": 6.5431,
       "median": 7.2732,
       "p75": 9.8175,
       "max": 81.6202
      },
      "mspsf phase-1 fusion": {
       "mean": 17487.3195,
       "p25": 8742.7479,
       "median": 9774.104,
       "p75": 27160.7929,
       "max": 51062.942
      },
      "buckets+support": {
       "mean": 13.1547,
       "p25": 4.4497,
       "median": 5.2814,
       "p75": 7.1309,
       "max": 151.326
      },
      "attribute checks": {
       "mean": 3.1521,
       "p25": 1.696,
       "median": 1.9602,
       "p75": 2.608,
       "max": 12.6347
      },
      "consistency+ledger": {
       "mean": 9.0758,
       "p25": 4.7163,
       "median": 5.4118,
       "p75": 7.2899,
       "max": 32.1103
      },
      "reputation+gate": {
       "mean": 0.3572,
       "p25": 0.0721,
       "median": 0.1185,
       "p75": 0.2031,
       "max": 4.3867
      },
      "db record+flush": {
       "mean": 1.1261,
       "p25": 0.2623,
       "median": 0.617,
       "p75": 1.3148,
       "max": 8.0412
      },
      "sort tracking": {
       "mean": 223.9366,
       "p25": 107.6547,
       "median": 124.856,
       "p75": 159.1226,
       "max": 883.4623
      }
     }
    }
   }
  ],
  "2": [
   {
    "axis": "agents",
    "x": 2,
    "title": "2 agents &times; 256 objects",
    "stages": {
     "modified": {
      "END-TO-END": {
       "mean": 101.2431,
       "p25": 99.9204,
       "median": 100.5778,
       "p75": 101.1343,
       "max": 120.0041
      },
      "decode": null,
      "kinematic checks": {
       "mean": 1.1487,
       "p25": 1.1177,
       "median": 1.1505,
       "p75": 1.1779,
       "max": 1.2239
      },
      "mspsf phase-1 fusion": {
       "mean": 98.0826,
       "p25": 96.8531,
       "median": 97.4674,
       "p75": 97.9583,
       "max": 116.8174
      },
      "buckets+support": {
       "mean": 0.7599,
       "p25": 0.7373,
       "median": 0.7536,
       "p75": 0.7795,
       "max": 0.8662
      },
      "attribute checks": {
       "mean": 0.3524,
       "p25": 0.3464,
       "median": 0.3532,
       "p75": 0.3589,
       "max": 0.3705
      },
      "consistency+ledger": {
       "mean": 0.7167,
       "p25": 0.7008,
       "median": 0.711,
       "p75": 0.7295,
       "max": 0.788
      },
      "reputation+gate": {
       "mean": 0.0204,
       "p25": 0.0194,
       "median": 0.0201,
       "p75": 0.0211,
       "max": 0.0283
      },
      "db record+flush": {
       "mean": 0.1624,
       "p25": 0.1515,
       "median": 0.1567,
       "p75": 0.1646,
       "max": 0.2201
      },
      "sort tracking": {
       "mean": 26.2538,
       "p25": 25.8291,
       "median": 26.1161,
       "p75": 26.502,
       "max": 28.8517
      }
     },
     "reference": {
      "END-TO-END": {
       "mean": 763.0553,
       "p25": 761.5235,
       "median": 763.2142,
       "p75": 764.4927,
       "max": 768.4662
      },
      "decode": null,
      "kinematic checks": {
       "mean": 1.1662,
       "p25": 1.1394,
       "median": 1.1699,
       "p75": 1.1962,
       "max": 1.2288
      },
      "mspsf phase-1 fusion": {
       "mean": 759.8932,
       "p25": 758.4952,
       "median": 760.0384,
       "p75": 761.4109,
       "max": 765.2861
      },
      "buckets+support": {
       "mean": 0.7449,
       "p25": 0.7284,
       "median": 0.753,
       "p75": 0.7713,
       "max": 0.8157
      },
      "attribute checks": {
       "mean": 0.3514,
       "p25": 0.3405,
       "median": 0.3503,
       "p75": 0.3599,
       "max": 0.3738
      },
      "consistency+ledger": {
       "mean": 0.714,
       "p25": 0.7041,
       "median": 0.7118,
       "p75": 0.7258,
       "max": 0.7756
      },
      "reputation+gate": {
       "mean": 0.0212,
       "p25": 0.0198,
       "median": 0.0214,
       "p75": 0.0224,
       "max": 0.0266
      },
      "db record+flush": {
       "mean": 0.1644,
       "p25": 0.1536,
       "median": 0.1643,
       "p75": 0.1731,
       "max": 0.2032
      },
      "sort tracking": {
       "mean": 26.3443,
       "p25": 25.8803,
       "median": 26.3077,
       "p75": 26.9336,
       "max": 27.3869
      }
     }
    }
   },
   {
    "axis": "agents",
    "x": 10,
    "title": "10 agents &times; 256 objects",
    "stages": {
     "modified": {
      "END-TO-END": {
       "mean": 593.2514,
       "p25": 589.3253,
       "median": 590.7701,
       "p75": 593.7035,
       "max": 627.3735
      },
      "decode": null,
      "kinematic checks": {
       "mean": 5.573,
       "p25": 5.5001,
       "median": 5.5672,
       "p75": 5.65,
       "max": 5.839
      },
      "mspsf phase-1 fusion": {
       "mean": 575.4688,
       "p25": 570.4101,
       "median": 572.8271,
       "p75": 575.9686,
       "max": 609.6916
      },
      "buckets+support": {
       "mean": 5.1496,
       "p25": 4.9747,
       "median": 5.1234,
       "p75": 5.21,
       "max": 5.9849
      },
      "attribute checks": {
       "mean": 1.7486,
       "p25": 1.7173,
       "median": 1.7388,
       "p75": 1.7699,
       "max": 1.9279
      },
      "consistency+ledger": {
       "mean": 5.062,
       "p25": 4.9745,
       "median": 5.0699,
       "p75": 5.0965,
       "max": 5.3138
      },
      "reputation+gate": {
       "mean": 0.0412,
       "p25": 0.0386,
       "median": 0.0404,
       "p75": 0.0433,
       "max": 0.0506
      },
      "db record+flush": {
       "mean": 0.2082,
       "p25": 0.1915,
       "median": 0.2018,
       "p75": 0.2147,
       "max": 0.2808
      },
      "sort tracking": {
       "mean": 135.4581,
       "p25": 132.9354,
       "median": 134.8017,
       "p75": 138.5951,
       "max": 142.5813
      }
     },
     "reference": {
      "END-TO-END": {
       "mean": 9631.3723,
       "p25": 9615.9468,
       "median": 9628.2243,
       "p75": 9649.5476,
       "max": 9669.6537
      },
      "decode": null,
      "kinematic checks": {
       "mean": 5.5535,
       "p25": 5.4684,
       "median": 5.5499,
       "p75": 5.6359,
       "max": 5.7928
      },
      "mspsf phase-1 fusion": {
       "mean": 9613.5421,
       "p25": 9597.5043,
       "median": 9610.526,
       "p75": 9631.4037,
       "max": 9651.9809
      },
      "buckets+support": {
       "mean": 5.2043,
       "p25": 5.1215,
       "median": 5.1961,
       "p75": 5.3096,
       "max": 5.5807
      },
      "attribute checks": {
       "mean": 1.7412,
       "p25": 1.7056,
       "median": 1.7475,
       "p75": 1.7608,
       "max": 1.8373
      },
      "consistency+ledger": {
       "mean": 5.0758,
       "p25": 5.0283,
       "median": 5.0774,
       "p75": 5.1168,
       "max": 5.2018
      },
      "reputation+gate": {
       "mean": 0.0392,
       "p25": 0.0372,
       "median": 0.0391,
       "p75": 0.0408,
       "max": 0.0546
      },
      "db record+flush": {
       "mean": 0.2161,
       "p25": 0.2062,
       "median": 0.2158,
       "p75": 0.2235,
       "max": 0.264
      },
      "sort tracking": {
       "mean": 132.2802,
       "p25": 130.7554,
       "median": 131.7261,
       "p75": 133.351,
       "max": 137.6566
      }
     }
    }
   }
  ]
 }
};
