// GENERATED by scripts/make_fusion_speedup_viz.py -- do not hand-edit.
// Re-run it after changing fusion.py/geometry.py to refresh fusion_speedup.html.
window.FUSION_SPEEDUP = {
  "generated_by": "scripts/make_fusion_speedup_viz.py",
  "measures": "fusion.mspsf phase-1 time, ms (geometry.compute_self_iou_mat + affinity/kappa)",
  "before_ref": "mmcooper_fuse.old.mspsf_old (HEAD minus the vectorized blocks)",
  "after_ref": "HEAD (38c9edcd)",
  "kds": "excluded (mspsf driven with kds_scores=None)",
  "repeats": 7,
  "warmup": 2,
  "seed": 0,
  "note": "measured in the emulated-x86 ros2_dev container; bar = median, whisker = 25-75th pct, line = best of N",
  "combos": [
    {
      "agents": 2,
      "objects": 30,
      "n": 60,
      "before_ms": 7.0373,
      "before_p25_ms": 7.0171,
      "before_p75_ms": 7.1845,
      "before_best_ms": 6.9687,
      "after_ms": 2.7857,
      "after_p25_ms": 2.7547,
      "after_p75_ms": 2.8209,
      "after_best_ms": 2.7515,
      "speedup": 2.53
    },
    {
      "agents": 2,
      "objects": 256,
      "n": 512,
      "before_ms": 248.2066,
      "before_p25_ms": 246.7582,
      "before_p75_ms": 249.2999,
      "before_best_ms": 245.7123,
      "after_ms": 28.0522,
      "after_p25_ms": 27.7906,
      "after_p75_ms": 28.424,
      "after_best_ms": 27.5383,
      "speedup": 8.85
    },
    {
      "agents": 10,
      "objects": 30,
      "n": 300,
      "before_ms": 131.0182,
      "before_p25_ms": 130.3871,
      "before_p75_ms": 137.3403,
      "before_best_ms": 130.0325,
      "after_ms": 19.6305,
      "after_p25_ms": 19.4996,
      "after_p75_ms": 20.0348,
      "after_best_ms": 19.4626,
      "speedup": 6.67
    },
    {
      "agents": 10,
      "objects": 256,
      "n": 2560,
      "before_ms": 6804.3155,
      "before_p25_ms": 6590.8403,
      "before_p75_ms": 6909.9849,
      "before_best_ms": 6526.2026,
      "after_ms": 339.8334,
      "after_p25_ms": 337.9021,
      "after_p75_ms": 386.6001,
      "after_best_ms": 331.4019,
      "speedup": 20.02
    }
  ]
};
