#!/usr/bin/env python3
"""
Snapshot one ego's most recent reputation trajectory for a peer into the JS
data file `visualizations/reputation_history.html` draws.

Usage:
    python3 make_reputation_history_viz.py                # ego 1 (repo default)
    python3 make_reputation_history_viz.py <agent_id>      # resolves the repo default path
    python3 make_reputation_history_viz.py <path_to.db>    # explicit database file

Re-run this after a demo run to refresh the figure with the latest data --
the HTML page never reads the database itself (see its own docstring for why),
so a stale run without re-running this script is a stale chart.

Stdlib only, same reasoning as tools/lichtblick/make_ground_glb.py: this is
meant to run wherever the .db file is, which is not guaranteed to be a
container with extra packages installed.
"""

import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from show_reputations import _resolve_db_path  # noqa: E402

import sqlite3  # noqa: E402

_OUT = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), '..', 'visualizations',
    'reputation_history_data.js',
)

# The most recent session, whichever source_id it belongs to: each demo run
# starts a fresh session per peer (see persistent_reputation_tracker.py), and
# concatenating sessions would splice unrelated runs into one trajectory. In
# the two-agent demo there is exactly one peer per ego, so "most recent
# session" and "agent 2, as judged by ego 1" are the same query -- this does
# not need to decode the hex-packed source_id key to know that.
_QUERY = '''
    SELECT r.r_new, r.ts
    FROM reputation_log r
    WHERE r.session_id = (SELECT MAX(id) FROM sessions)
    ORDER BY r.id
'''


def _extract(db_path: str) -> list[tuple[float, float]]:
    conn = sqlite3.connect(db_path)
    try:
        cols = [row[1] for row in conn.execute('PRAGMA table_info(reputation_log)')]
        if 'ts' not in cols:
            raise SystemExit(
                f'{db_path}: no ts column -- written by an agent build too old '
                'for this chart (it needs real timestamps, not just frame order)'
            )
        return conn.execute(_QUERY).fetchall()
    finally:
        conn.close()


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(f'usage: {argv[0]} [agent_id | path_to.db]', file=sys.stderr)
        return 2

    db_path = _resolve_db_path(argv[1])
    if not os.path.exists(db_path):
        print(f'no database at: {db_path}', file=sys.stderr)
        return 1

    rows = _extract(db_path)
    if not rows:
        t, r = [], []
    else:
        t0 = rows[0][1]
        t = [ts - t0 for _, ts in rows]
        r = [r_new for r_new, _ in rows]

    with open(_OUT, 'w') as fh:
        fh.write('// GENERATED by make_reputation_history_viz.py -- do not hand-edit.\n')
        fh.write('// Re-run it after a demo run to refresh reputation_history.html.\n')
        fh.write('window.REPUTATION_HISTORY = ')
        json.dump({'source_db': db_path, 't': t, 'r': r}, fh)
        fh.write(';\n')

    print(f'{db_path}: {len(rows)} row(s) -> {_OUT}')
    if not rows:
        print('(no reputation rows yet -- the chart will say so instead of drawing)')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
