//
// Generated file, do not edit! Created by opp_msgtool 6.0 from messages/SdsmPayload.msg.
//

#ifndef __VEINS_ROS_V2V__MESSAGES_SDSMPAYLOAD_M_H
#define __VEINS_ROS_V2V__MESSAGES_SDSMPAYLOAD_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif


namespace veins_ros_v2v {
namespace messages {

class SdsmPayload;

}  // namespace messages
}  // namespace veins_ros_v2v


namespace veins_ros_v2v {
namespace messages {

/**
 * Class generated from <tt>messages/SdsmPayload.msg:8</tt> by opp_msgtool.
 * <pre>
 * packet SdsmPayload
 * {
 *     string payload;
 * 
 *     // === Legacy fields (greedy, AoI, neighbor tracking) ===
 *     int senderNodeIndex = -1;
 *     double senderX = 0;
 *     double senderY = 0;
 *     double senderSpeed = 0;
 *     double senderHeading = 0;
 *     double sendTimestamp = 0;
 *     long message_id = 0;   // global id to link TX and RX events
 * 
 *     // === SDSM header (CPX-SDSM SensorDataSharingMessage) ===
 *     int msg_cnt = 0;              // 0-127, wraps
 *     int source_id[4];             // 4-byte anonymized sender ID
 *     int equipment_type = 2;        // 0=unknown, 1=RSU, 2=OBU, 3=VRU
 * 
 *     // Reference position (sender) — meters in sim
 *     double ref_pos_x = 0;
 *     double ref_pos_y = 0;
 *     double ref_pos_z = 0;
 * 
 *     // Timestamp (CPX DDateTime)
 *     int sdsm_day = 1;              // 1-31
 *     long sdsm_time_of_day_ms = 0;   // ms since midnight
 * 
 *     // === Detected objects array (up to 16 per J3224) ===
 *     int numObjects = 0;            // actual count of objects in this message (0..16)
 *     int obj_type[16];              // 1=vehicle per object
 *     int object_id[16];             // node index of detected object
 *     int offset_x[16];              // position offset from ref_pos, 0.1 m units
 *     int offset_y[16];
 *     int offset_z[16];
 *     int obj_speed[16];             // 0.02 m/s units (J2735)
 *     int obj_heading[16];           // 0.0125 deg units, 28800=unavailable
 * }
 * </pre>
 */
class SdsmPayload : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string payload;
    int senderNodeIndex = -1;
    double senderX = 0;
    double senderY = 0;
    double senderSpeed = 0;
    double senderHeading = 0;
    double sendTimestamp = 0;
    long message_id = 0;
    int msg_cnt = 0;
    int source_id[4] = {0};
    int equipment_type = 2;
    double ref_pos_x = 0;
    double ref_pos_y = 0;
    double ref_pos_z = 0;
    int sdsm_day = 1;
    long sdsm_time_of_day_ms = 0;
    int numObjects = 0;
    int obj_type[16] = {0};
    int object_id[16] = {0};
    int offset_x[16] = {0};
    int offset_y[16] = {0};
    int offset_z[16] = {0};
    int obj_speed[16] = {0};
    int obj_heading[16] = {0};

  private:
    void copy(const SdsmPayload& other);

  protected:
    bool operator==(const SdsmPayload&) = delete;

  public:
    SdsmPayload(const char *name=nullptr, short kind=0);
    SdsmPayload(const SdsmPayload& other);
    virtual ~SdsmPayload();
    SdsmPayload& operator=(const SdsmPayload& other);
    virtual SdsmPayload *dup() const override {return new SdsmPayload(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);

    virtual int getSenderNodeIndex() const;
    virtual void setSenderNodeIndex(int senderNodeIndex);

    virtual double getSenderX() const;
    virtual void setSenderX(double senderX);

    virtual double getSenderY() const;
    virtual void setSenderY(double senderY);

    virtual double getSenderSpeed() const;
    virtual void setSenderSpeed(double senderSpeed);

    virtual double getSenderHeading() const;
    virtual void setSenderHeading(double senderHeading);

    virtual double getSendTimestamp() const;
    virtual void setSendTimestamp(double sendTimestamp);

    virtual long getMessage_id() const;
    virtual void setMessage_id(long message_id);

    virtual int getMsg_cnt() const;
    virtual void setMsg_cnt(int msg_cnt);

    virtual size_t getSource_idArraySize() const;
    virtual int getSource_id(size_t k) const;
    virtual void setSource_id(size_t k, int source_id);

    virtual int getEquipment_type() const;
    virtual void setEquipment_type(int equipment_type);

    virtual double getRef_pos_x() const;
    virtual void setRef_pos_x(double ref_pos_x);

    virtual double getRef_pos_y() const;
    virtual void setRef_pos_y(double ref_pos_y);

    virtual double getRef_pos_z() const;
    virtual void setRef_pos_z(double ref_pos_z);

    virtual int getSdsm_day() const;
    virtual void setSdsm_day(int sdsm_day);

    virtual long getSdsm_time_of_day_ms() const;
    virtual void setSdsm_time_of_day_ms(long sdsm_time_of_day_ms);

    virtual int getNumObjects() const;
    virtual void setNumObjects(int numObjects);

    virtual size_t getObj_typeArraySize() const;
    virtual int getObj_type(size_t k) const;
    virtual void setObj_type(size_t k, int obj_type);

    virtual size_t getObject_idArraySize() const;
    virtual int getObject_id(size_t k) const;
    virtual void setObject_id(size_t k, int object_id);

    virtual size_t getOffset_xArraySize() const;
    virtual int getOffset_x(size_t k) const;
    virtual void setOffset_x(size_t k, int offset_x);

    virtual size_t getOffset_yArraySize() const;
    virtual int getOffset_y(size_t k) const;
    virtual void setOffset_y(size_t k, int offset_y);

    virtual size_t getOffset_zArraySize() const;
    virtual int getOffset_z(size_t k) const;
    virtual void setOffset_z(size_t k, int offset_z);

    virtual size_t getObj_speedArraySize() const;
    virtual int getObj_speed(size_t k) const;
    virtual void setObj_speed(size_t k, int obj_speed);

    virtual size_t getObj_headingArraySize() const;
    virtual int getObj_heading(size_t k) const;
    virtual void setObj_heading(size_t k, int obj_heading);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SdsmPayload& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SdsmPayload& obj) {obj.parsimUnpack(b);}


}  // namespace messages
}  // namespace veins_ros_v2v


namespace omnetpp {

template<> inline veins_ros_v2v::messages::SdsmPayload *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins_ros_v2v::messages::SdsmPayload*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __VEINS_ROS_V2V__MESSAGES_SDSMPAYLOAD_M_H

